"""empty message

Revision ID: 02572e0099de
Revises: 345aa4573e29
Create Date: 2018-04-01 11:25:55.739876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02572e0099de'
down_revision = '345aa4573e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follwers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follwers')
    # ### end Alembic commands ###
