"""aboutme and last field in user table

Revision ID: 345aa4573e29
Revises: a920b8e5b1b8
Create Date: 2018-03-30 14:32:38.349013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345aa4573e29'
down_revision = 'a920b8e5b1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aboutme', sa.String(length=400), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'aboutme')
    # ### end Alembic commands ###
